Adjust error output.

diff --git a/bin/gb b/bin/gb
--- a/bin/gb
+++ b/bin/gb
@@ -82,7 +82,7 @@ USAGE
 }
 
 fail() { 
-  echo -e "\e[31mERROR: $*\e[0m" >&2
+  echo -e "\e[31mERROR:\e[0m $*" >&2
   exit 1
 }
 
@@ -115,13 +115,13 @@ find::env::file() {
       sort -d | head -1
   ))
 
-  [[ ${#_yamls[@]} > 1 ]] ||
+  [[ ${#_yamls[@]} > 0 ]] ||
     fail "${FUNCNAME}: No bosh env files found matching regex '${_env}'"
+
   [[ ${#_yamls[@]} < 2 ]] ||
     fail "${FUNCNAME}: Multiple bosh env files found matching regex '${_env}': ${_yamls[*]}"
-  [[ ${#_yamls[@]} < 2 ]] ||
-    fail "${FUNCNAME}: Expected only one env files to match regex '${_env}', found:" "${_yamls[@]}"
-  [[ -s "${_yamls[0]}" ]] || fail "${_env_file} is empty!"
+
+  [[ -s "${_yamls[0]}" ]] || fail "The env file '${_env_file}' is empty!"
 
   _env_file="${_yamls[0]}"
 
@@ -214,6 +214,7 @@ bosh::do() {
 
 bosh::deps() {
   local _env="${1}"
+
   shift ||
     fail "${FUNCNAME}: bosh::deps requires an environment name."
 
@@ -222,6 +223,7 @@ bosh::deps() {
 
 bosh::dep() {
   local _env=${1} _d
+
   shift ||
     fail "${FUNCNAME}: bosh::dep requires an environment name."
 
@@ -232,6 +234,7 @@ bosh::dep() {
 
 bosh::manifest() {
   local _env="${1}" _dep_regex="$2"
+
   shift 2 ||
     fail "${FUNCNAME}: bosh::manifest requires an env regex followed by a deployment regex."
 
@@ -240,9 +243,9 @@ bosh::manifest() {
 
 bosh::vms::do() {
   local _env_regex="$1" _dep_regex="$2"
+
   shift 2 ||
     fail "${FUNCNAME}: bosh::vms requires an env regex followed by a deployment regex."
-
   vms=($(
     bosh::do "${_env}" -d "${_dep}" vms --json |
     jq -r '.Tables[].Rows[].instance' | 
