Refactored to a __parse::args. Adjusted pg secrets paths to contract.

diff --git a/bin/ocfp b/bin/ocfp
--- a/bin/ocfp
+++ b/bin/ocfp
@@ -35,76 +35,120 @@ exit 0
 
 fail() { echo -e "$*" >&2 ; exit 1 ; }
 
+__parse::args() {
+  local _action
+  while [[ $# > 0 ]]
+  do
+    _action="${1}" ; shift
+    case ${_action} in
+      (vault-prefix)
+        export OCFP_VAULT_PREFIX="${1}" # override default of secret/
+        ;;
+      (region)
+        export OCFP_REGION=$1 # ex: us-east-1, us-west-2
+        shift || fail "${0//*/} ... region <region>"
+        ;;
+      (kit)
+        export OCFP_KIT=$1
+        shift || fail "${0//*/} ... kit <name>"
+        case ${OCFP_KIT} in
+          (bosh|cf|blacksmith|shield|concourse|autoscaler|scheduler|vault|jumpbox) true ;;
+          (*) fail "Unsupported kit: ${OCFP_KIT}" ;;
+        esac
+        ;;
+      (env|name)
+        export OCFP_ENV_NAME=${1//.yml}
+        shift || fail "${0//*/} ... name <env-name> # ex: ocfp-codex-mgmt-us-east-1 / ocfp-codex-us-east-1"
+        ;;
+      (iaas)
+        export OCFP_IAAS=$1
+        shift || fail "${0//*/} ... iaas <aws|azure|gcp|openstack|vsphere|warden>"
+        case ${OCFP_IAAS} in
+          #NOTE: Upstream are alicloud aws azure cloudstack docker gcp openstack softlayer vcloud virtualbox vsphere warden
+          (aws|azure|gcp|openstack|vsphere|warden) true ;;
+          (*) fail "Unsupported IAAS type: ${OCFP_IAAS}" ;;
+        esac
+        ;;
+      (*)
+        usage
+        ;;
+    esac
+  done
+}
+
+__init::pg() {
+  __init::parse::args "$@"
+  echo -e "Initializing PG databases for env...\n\t-> ${OCFP_ENV_NAME}.yml"
+  bash "${templates_path}/pg/init" env "${OCFP_ENV_NAME}" kit "${OCFP_KIT}" region "${OCFP_REGION}"
+}
+
+__init::env() {
+  local _action
+  while [[ $# > 0 ]]
+  do
+    _action="${1}" ; shift
+    case ${_action} in
+      (vault-prefix)
+        export OCFP_VAULT_PREFIX="${1}" # override default of secret/
+        ;;
+      (region)
+        export OCFP_REGION=$1 # ex: us-east-1, us-west-2
+        shift || fail "${0//*/} ... region <region>"
+        ;;
+      (kit)
+        export OCFP_KIT=$1
+        shift || fail "${0//*/} ... kit <name>"
+        case ${OCFP_KIT} in
+          (bosh|cf|blacksmith|shield|concourse|autoscaler|scheduler|vault|jumpbox) true ;;
+          (*) fail "Unsupported kit: ${OCFP_KIT}" ;;
+        esac
+        ;;
+      (e|name)
+        export OCFP_ENV_NAME=${1//.yml}
+        shift || fail "${0//*/} ... name <env-name> # ex: ocfp-codex-mgmt-us-east-1 / ocfp-codex-us-east-1"
+        ;;
+      (iaas)
+        export OCFP_IAAS=$1
+        shift || fail "${0//*/} ... iaas <aws|azure|gcp|openstack|vsphere|warden>"
+        case ${OCFP_IAAS} in
+          #NOTE: Upstream are alicloud aws azure cloudstack docker gcp openstack softlayer vcloud virtualbox vsphere warden
+          (aws|azure|gcp|openstack|vsphere|warden) true ;;
+          (*) fail "Unsupported IAAS type: ${OCFP_IAAS}" ;;
+        esac
+        ;;
+      (*)
+        usage
+        ;;
+    esac
+  done
+
+  [[ -n ${OCFP_ENV_NAME} ]] || fail "'env <name>' must be given"
+  [[ -n ${OCFP_KIT} ]] || fail "'kit <name>' must be given"
+  [[ -n ${OCFP_REGION} ]] || fail "'region <region>' must be given"
+
+  case ${OCFP_KIT} in
+    (bosh)
+      [[ -n ${OCFP_IAAS} ]] || fail "'iaas <aws|gcp|azure>' must be given"
+      ;;
+  esac
+
+  if [[ -s ${OCFP_ENV_NAME}.yml ]] 
+  then
+    fail "ERROR: ${OCFP_ENV_NAME}.yml already exists, rename it and re-run."
+  else
+    echo -e "Generating Genesis Env File From Kit Template...\n\t-> ${OCFP_ENV_NAME}.yml"
+    bash "${templates_path}/env/${OCFP_KIT}" > ${OCFP_ENV_NAME}.yml
+    exit $?
+  fi
+}
+
 templates_path="${0%\/ocfp}/templates"
 cmd=$1 
 shift || usage
 case ${cmd} in
-  (init-pg)
-    echo "TODO: Merge with pg init script -> ocpf-init"
-      echo -e "Initializing PG databases for env...\n\t-> ${OCFP_ENV_NAME}.yml"
-      bash "${templates_path}/pg/init"
-    ;;
-  (init-env)
-    while [[ $# > 0 ]]
-    do
-      action=$1 ; shift
-      case ${action} in
-        (vault-prefix)
-          export OCFP_VAULT_PREFIX="${1}" # override default of secret/
-          ;;
-        (region)
-          export OCFP_REGION=$1 # ex: us-east-1, us-west-2
-          shift || fail "${0//*/} ... region <region>"
-          ;;
-        (kit)
-          export OCFP_KIT=$1
-          shift || fail "${0//*/} ... kit <name>"
-          case ${OCFP_KIT} in
-            (bosh|cf|blacksmith|shield|concourse|autoscaler|scheduler|vault|jumpbox) true ;;
-            (*) fail "Unsupported kit: ${OCFP_KIT}" ;;
-          esac
-          ;;
-        (name)
-          export OCFP_ENV_NAME=${1//.yml}
-          shift || fail "${0//*/} ... name <env-name> # ex: ocfp-codex-mgmt-us-east-1 / ocfp-codex-us-east-1"
-          ;;
-        (iaas)
-          export OCFP_IAAS=$1
-          shift || fail "${0//*/} ... iaas <aws|azure|gcp|openstack|vsphere|warden>"
-          case ${OCFP_IAAS} in
-            #NOTE: Upstream are alicloud aws azure cloudstack docker gcp openstack softlayer vcloud virtualbox vsphere warden
-            (aws|azure|gcp|openstack|vsphere|warden) true ;;
-            (*) fail "Unsupported IAAS type: ${OCFP_IAAS}" ;;
-          esac
-          ;;
-        (*)
-          usage
-          ;;
-      esac
-    done
-
-    [[ -n ${OCFP_ENV_NAME} ]] || fail "'env <name>' must be given"
-    [[ -n ${OCFP_KIT} ]] || fail "'kit <name>' must be given"
-    [[ -n ${OCFP_REGION} ]] || fail "'region <region>' must be given"
-
-    case ${OCFP_KIT} in
-      (bosh)
-        [[ -n ${OCFP_IAAS} ]] || fail "'iaas <aws|gcp|azure>' must be given"
-        ;;
-    esac
-
-    if [[ -s ${OCFP_ENV_NAME}.yml ]] 
-    then
-      fail "ERROR: ${OCFP_ENV_NAME}.yml already exists, rename it and re-run."
-    else
-      echo -e "Generating Genesis Env File From Kit Template...\n\t-> ${OCFP_ENV_NAME}.yml"
-      bash "${templates_path}/env/${OCFP_KIT}" > ${OCFP_ENV_NAME}.yml
-      exit $?
-    fi
-    ;;
-  (*)
-    usage
-    ;;
+  (init-pg) __init::pg "$@" ;;
+  (init-env) __init::env "$@" ;;
+  (*) usage ;;
 esac
 
 
diff --git a/templates/pg/init b/templates/pg/init
--- a/templates/pg/init
+++ b/templates/pg/init
@@ -35,7 +35,7 @@ pg::psql() {
   \psql "${PG_URI}/${_db}" "$*"
 }
 
-set_contract_secrets() {
+pg::set::contract::secrets() {
   local _d="$1"
   local _h="$2"
   local _u="$3"
@@ -58,29 +58,29 @@ set_contract_secrets() {
     &> /dev/null # Do not leak credentials to output
 }
 
-prepare() {
+pg::prepare() {
   local tf_prefix="${OCFP_VAULT_PREFIX:-secret/}/tf/${OCFP_REGION//-/\/}"
   local src_path="${tf_prefix}/ocfp/${env_type//-/\/}/dbs/${kit}"
   local dst_path="${OCFP_VAULT_PREFIX}/${env_name//-/\/}/${kit}"
 
-  PGHOSTNAME="$(safe get "${src_path}/db/hostname")"
-  PGUSERNAME="$(safe get "${src_path}/db/postgres_username")"
-  PGPASSWORD="$(safe get "${src_path}/db/postgres_password")"
+  PGHOSTNAME="$(safe get "${src_path}:hostname")"
+  PGUSERNAME="$(safe get "${src_path}:postgres_username")"
+  PGPASSWORD="$(safe get "${src_path}:postgres_password")"
 
   [[ -n ${PGHOSTNAME} ]] || 
-    fail "Could not find hostname at ${src_path}/db:hostname"
+    fail "Could not find hostname at ${src_path}:hostname"
 
   [[ -n ${PGUSERNAME} ]] || 
-    fail "Could not find username at ${src_path}/db:postgres_username"
+    fail "Could not find username at ${src_path}:postgres_username"
 
   [[ -n ${PGPASSWORD} ]] || 
-    fail "Could not find password at ${src_path}/db:postgres_password"
+    fail "Could not find password at ${src_path}:postgres_password"
 
   PG_URI="postgresql://${PGUSERNAME}:${PGPASSWORD}@${PGHOSTNAME}:5432"
 
   local _db
   for _db in ${@}; do
-    set_contract_secrets "${_db}"
+    pg::set::contract::secrets "${_db}"
 
     local _u="$(safe get "${src_path}:${_db}_username")"
     local _p="$(safe get "${src_path}:${_db}_password")"
@@ -103,68 +103,71 @@ prepare() {
   done
 }
 
-logs_path="$HOME/.ocfp/logs"
-mkdir -p ${logs_path}
+__parse::args() {
+  while [[ $# > 0 ]]
+  do
+    action=$1 ; shift
+    case "${action}" in
+      (region)
+        OCFP_REGION=$1
+        shift || fail "${0//*/} ... env <name>"
+        ;;
+      (env) 
+        env_name="$1" 
+        shift || fail "${0//*/} ... env <name>"
+        ;;
+      (kit) 
+        kit="$1" 
+        shift || fail "${0//*/} ... kit <name>"
+        case ${kit} in
+          (bosh|cf|blacksmith|shield|concourse|autoscaler|scheduler|vault|jumpbox) true ;;
+          (*) fail "Unsupported kit: ${kit}" ;;
+        esac
+        ;;
+      (*) fail "$(usage)" ;;
+    esac
+  done
+  
+  env_name="${env_name%.yml}"
+  case "${env_name}" in
+    (*-mgmt-*) env_type="mgmt" ;;
+    (*)        env_type="ocf"  ;;
+  esac
+  
+  [[ -n ${OCFP_REGION} ]] || fail "OCFP_REGION must be set and exported."
+  [[ -n ${env_name} ]] || fail "'env <name>' required"
+  [[ -n ${kit} ]]      || fail "'kit <name>' required"
+  [[ -n ${VAULT_NAMESPACE} ]] && export VAULT_NAMESPACE
+}
 
 timestamp="$(date +%Y-%m-%dT%H:%M:%S)"
-
+logs_path="$HOME/.ocfp/logs"
+mkdir -p ${logs_path}
 exec &> >(tee -a "${logs_path}/ocfp-init-pg.${timestamp}.log")
-
-[[ -n ${VAULT_NAMESPACE} ]] && export VAULT_NAMESPACE
-
-[[ -n ${OCFP_REGION} ]] || fail "OCFP_REGION must be set and exported."
 
 [[ $# > 1 ]] || fail "$(usage)"
 
-# TODO: change parameters to specify and case: env <env-name> kit <kit-name>
-while [[ $# > 0 ]]
-do
-  action=$1 ; shift
-  case "${action}" in
-    (env) 
-      env_name="$1" 
-      shift || fail "${0//*/} ... env <name>"
-      ;;
-    (kit) 
-      kit="$1" 
-      shift || fail "${0//*/} ... kit <name>"
-      case ${kit} in
-        (bosh|cf|blacksmith|shield|concourse|autoscaler|scheduler|vault|jumpbox) true ;;
-        (*) fail "Unsupported kit: ${kit}" ;;
-      esac
-      ;;
-    (*) fail "$(usage)" ;;
-  esac
-done
-
-env_name="${env_name%.yml}"
-case "${env_name}" in
-  (*-mgmt-*) env_type="mgmt" ;;
-  (*)        env_type="ocf"  ;;
-esac
-
-[[ -n ${env_name} ]] || fail "'env <name>' required"
-[[ -n ${kit} ]]      || fail "'kit <name>' required"
+__parse::args "$@"
 
 case "${kit}" in
   (bosh)
-    prepare bosh uaa credhub
+    pg::prepare bosh uaa credhub
     ;;
   (cf) # Question, is it routing_api or routing-api?
-    prepare cloud_controller credhub diego locket network_connectivity network_policy routing_api uaa
+    pg::prepare cloud_controller credhub diego locket network_connectivity network_policy routing_api uaa
     ;;
   (autoscaler)
     kit="cf-app-autoscaler" # :/ # Contract FAIL
-    prepare autoscaler # NOTE: BUG: safe set ${safe_path}/cf-app-autoscaler/db password="" # Contract FAIL
+    pg::prepare autoscaler # NOTE: BUG: safe set ${safe_path}/cf-app-autoscaler/db password="" # Contract FAIL
     ;;
   (scheduler)
-    prepare scheduler
+    pg::prepare scheduler
     ;;
   (stratos)
-    prepare stratos # console_db <- default, Can we make this stratos to align with the contract?
+    pg::prepare stratos # console_db <- default, Can we make this stratos to align with the contract?
     ;;
   (concourse)
-    prepare concourse # ats <- default, Can we make this concourse to align with the contract?
+    pg::prepare concourse # ats <- default, Can we make this concourse to align with the contract?
     ;;
   (*)
     fail "$(usage)"
