Added test tcp

diff --git a/test/blacksmith b/test/blacksmith
--- a/test/blacksmith
+++ b/test/blacksmith
@@ -10,15 +10,15 @@
 #
 
 # TODO: move commands output to logs file.
-# TODO: print report of passed / failed tests.
+# TODO: collect and print report of passed / failed tests.
 
 ################################################################################
 # Functions
 ################################################################################
  
-fail() { echo -e "\e[31mERROR:\e[0m $*" >&2 ; exit 1 ; }
+fail()  { echo -e "\e[31mERROR:\e[0m $*" >&2 ; exit 1 ; }
 
-run() { echo -e "\$ $*" >&2; "$@"; }
+run()   { echo -e "\e[32m\$\e[0m $*"; "$@"; }
 
 debug() { [[ -z ${DEBUG:-} ]] || echo -e "\e[93mDEBUG\e[0m: $*" >&2 ; }
 
@@ -82,7 +82,7 @@ apps::fetch() {
     then true # TODO: curl -sOL ${RMQ_APP_URL}/${archive}
     fi
     unzip ${apps_path}/${archive} ||
-      fail "Unable to unarchive /opt/ocfp/apps/${archive}"
+      fail "Unable to unarchive ${aps_path}/${archive}"
   fi
 }
 
