Handle unziping properly.

diff --git a/test/blacksmith b/test/blacksmith
--- a/test/blacksmith
+++ b/test/blacksmith
@@ -83,8 +83,8 @@ apps::fetch() {
       )
     fi
     ( cd ${apps_path}
-      run unzip /opt/ocfp/apps/${archive}
-    )
+      unzip ${apps_path}/${archive}
+    ) || fail "Unable to unarchive /opt/ocfp/apps/${archive}"
   fi
 }
 
