Add error checking. Do not prompt for delete.

diff --git a/test/nfs b/test/nfs
--- a/test/nfs
+++ b/test/nfs
@@ -83,6 +83,8 @@ parse::args() {
         ;;
     esac
   done
+  [[ -n ${env_name} ]]   || fail "... env <name>"
+  [[ -n ${#spaces[@]} ]] || fail "At least one space must be given."
 }
 
 nfs::config(){
@@ -157,7 +159,7 @@ clean::up() {
 
     run cf target -o system -s ${space}
 
-    run cf delete-service ${service_name}
+    run cf delete-service ${service_name} -f
 
     run cf delete ${app_name} -f
   done
diff --git a/test/smb b/test/smb
--- a/test/smb
+++ b/test/smb
@@ -81,6 +81,9 @@ parse::args() {
         ;;
     esac
   done
+
+  [[ -n ${env_name} ]]   || fail "... env <name>"
+  [[ -n ${#spaces[@]} ]] || fail "At least one space must be given."
 }
 
 app::create::bind::smb() {
@@ -145,7 +148,7 @@ clean::up() {
 
     run cf target -o system -s ${space}
 
-    run cf delete-service ${service_name}
+    run cf delete-service ${service_name} -f
 
     run cf delete ${app_name} -f
   done
